spdx_json_generator = """
import os
import time
import json
import pathlib
from glob import glob
from datetime import datetime, timezone
from conan import conan_version
from conan.errors import ConanException
from conan.api.output import ConanOutput


def generate_sbom(graph, **kwargs):
    name = graph.root.name if graph.root.name else "CLI"
    version = "SPDX-2.2"
    date = datetime.fromtimestamp(time.time(), tz=timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')
    packages = []
    files = []
    relationships = []

    # --- Root node ---
    if graph.root.recipe != "Cli":
        conan_data = graph.root.conanfile.conan_data
        url_location = conan_data.get("sources", {}).get(graph.root.conanfile.version, {}).get("url", {}) if conan_data else None
        checksum = conan_data.get("sources", {}).get(graph.root.conanfile.version, {}).get("sha256", {}) if conan_data else None
        packages.extend([
            {
                "name": graph.root.ref.name,
                "SPDXID": f"SPDXRef-{graph.root.ref}",
                "version": str(graph.root.ref.version),
                "downloadLocation": graph.root.conanfile.url or "NOASSERTION",
                "homePage": graph.root.conanfile.homepage or "NOASSERTION",
                "licenseConcluded": graph.root.conanfile.license or "NOASSERTION",
                "licenseDeclared": "NOASSERTION",
                "copyrightText": "NOASSERTION",
                "description": graph.root.conanfile.description or "NOASSERTION",
                "comment":  f"This is the {graph.root.ref.name} package in the remote" # TODO It could be a local package

            },
            {
                "name": f"{graph.root.pref} binary",
                "SPDXID": f"SPDXRef-binary-{graph.root.ref}",
                "downloadLocation": graph.root.remote.url if graph.root.remote else "NONE",
                "licenseConcluded": graph.root.conanfile.license or "NOASSERTION",
                "licenseDeclared": "NOASSERTION",
                "copyrightText": "NOASSERTION",
                "comment": f"This is the {graph.root.ref} binary generated by conan"
            },
            {
                "name": f"{graph.root.ref.name} upstream",
                "SPDXID": f"SPDXRef-resource-{graph.root.ref}",
                "downloadLocation": url_location or "NONE",
                **({"checksum": {
                        "algorithm": "SHA256",
                        "checksumValue": checksum
                    }} if checksum else {}),
                "licenseConcluded": graph.root.conanfile.license or "NOASSERTION",
                "licenseDeclared": "NOASSERTION",
                "copyrightText": "NOASSERTION",
                "comment": f"This is the {graph.root.ref.name} release file"
            }])

        relationships.extend([{
            "spdxElementId": f"SPDXRef-binary-{graph.root.ref}",
            "relationshipType": "DEPENDS_ON",
            "relatedSpdxElement": f"SPDXRef-binary-{d.dst.ref}",
        }for d in graph.root.dependencies])

        relationships.append({
            "spdxElementId": f"SPDXRef-{graph.root.ref}",
            "relationshipType": "GENERATES",
            "relatedSpdxElement": f"SPDXRef-binary-{graph.root.ref}",
        })

        exported_path = graph.root.conanfile.recipe_folder # /e folder
        external_files = [f for f in glob(os.path.join(exported_path, "**", "*"), recursive=True) if not f.endswith('/')] if exported_path else []

        try:
            with open(os.path.join(graph.root.conanfile.recipe_folder, "conanmanifest.txt")) as conanmanifest:
                external_files.extend([os.path.join(exported_path[:-1], *line.split(" ")[0][:-1].split("/")) for line in conanmanifest.readlines()[2:]])
        except Exception:
            pass

        for i, file_name in enumerate(external_files):
            checksum = None
            files.append(
                {
                    "fileName": file_name,
                    "SPDXID": f"SPDXRef-file-{graph.root.ref}-{i}",
                    **({"checksums":{
                            "algorithm": "SHA256",
                            "checksumValues": checksum,
                        }} if checksum else {}),
                    "licenseConcluded": "NOASSERTION",
                    "copyrightText": "NOASSERTION"
                }
            )
            relationships.append({
                "spdxElementId": f"SPDXRef-{graph.root.ref}",
                "relationshipType": "CONTAINS",
                "relatedSpdxElement": f"SPDXRef-file-{graph.root.ref}-{i}",
            })

    # --- Just the binaries for dependencies ---
    for node in graph.nodes[1:]:
        conan_data = node.conanfile.conan_data
        url_location = conan_data.get("sources", {}).get(node.conanfile.version, {}).get("url", {}) if conan_data else None
        checksum = conan_data.get("sources", {}).get(node.conanfile.version, {}).get("sha256", {}) if conan_data else None
        packages.extend([
            {
                "name": f"{node.pref} binary",
                "SPDXID": f"SPDXRef-binary-{node.ref}",
                "downloadLocation": node.remote.url if node.remote else "NONE",
                "licenseConcluded": node.conanfile.license or "NOASSERTION",
                "licenseDeclared": "NOASSERTION",
                "copyrightText": "NOASSERTION",
                "comment": f"This is the {node.ref} binary generated by conan"
            }])

        relationships.extend([{
            "spdxElementId": f"SPDXRef-binary-{node.ref}",
            "relationshipType": "DEPENDS_ON",
            "relatedSpdxElement": f"SPDXRef-binary-{d.dst.ref}",
        }for d in node.dependencies])


    # https://spdx.github.io/spdx-spec/v2.2.2/package-information/
    data = {
        "SPDXVersion": "SPDX-2.2",
        "dataLicense": "CC0-1.0",
        "SPDXID": "SPDXRef-DOCUMENT",
        "documentName": f"{name}-{version}",
        "documentNamespace": f"http://spdx.org/spdxdocs/{name}-{version}-{date}", # the date or hash to make it unique
        "creator": f"Tool: Conan-{conan_version}",
        "created": date, #YYYY-MM-DDThh:mm:ssZ
        "packages": packages,
        **({"files": files} if files else {}),
        **({"relationships": relationships} if relationships else {}),
    }
    try:
        metadata_folder = graph.root.conanfile.package_metadata_folder
        with open(os.path.join(metadata_folder, f"{name}-{graph.root.ref.version if graph.root.ref else "local"}.spdx.json"), 'w') as f:
            json.dump(data, f, indent=4)
        ConanOutput().success(f"SPDX CREATED - {graph.root.conanfile.package_metadata_folder}")
    except Exception as e:
        ConanException("error generating spdx file")
"""
